### ISSUE TITLE
How to avoid stripping HTML for content body

### ISSUE THREAD

**Issue by Hissvard** [zackslash/PHP-Web-Article-Extractor#13]
I've been using this for a project and found it absolutely great.
One thing I'd like to know is whether it's possible to avoid stripping HTML tags from the body of the article.

**Comment by zackslash** [comment]
Hi Hissvard,
I'm interested in your use case for this feature?
Currently HTML is stripped out of the process fairly early on (In the parsing process).
It is something I can keep in mind future versions or would be happy to accept a pull request.

**Comment by Hissvard** [comment]
I simply need to show the scraped content inside of an email, and it doesn't look as good with text only.
Not something that's vital, don't worry, I was just wondering whether there was some quick way to do it but I was missing on it.
